version: '3'

services:
  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=8787
      - MONGO_URI=mongodb+srv://rysbekdossayev:Laravel5@cluster0.guazwsy.mongodb.net/?retryWrites=true&w=majority
      - AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=YOUR_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME=2024-narxoz-mean-bucket
    ports:
      - "8787:8787"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
